### ISSUE TITLE
Add a README

### ISSUE THREAD

**Issue by joshrowley** [wismer/sunnyside-citywide#2]
Hey Matt,

I work with @kylemac, and he asked us to come take a look at this. I suggest you add more detail into the README. Anyone who comes to look at your repo should be able to get some context on what the project is all about (you can summarize the note you wrote to us), and then instructions on how to set it up and run it.

**Comment by kylemac** [comment]
hilarious reinforcement to https://github.com/wismer/sunnyside-citywide/issues/1 . @joshrowley filed this at the exact same time as me. Just shows how important this really is! :+1:

**Comment by wismer** [comment]
Would it be necessary to show a sample of the text that's being parsed in the PDF's and/or the EDI files? I'd have to censor some of them for HIPAA reasons, but I think the general gist may help?

**Comment by kylemac** [comment]
yeah this would be excellent. a common convention would be to have an `examples` directory; this would be in lieu of [unit testing](http://en.wikibooks.org/wiki/Ruby_Programming/Unit_testing).

**Comment by joshrowley** [comment]
Looking really great, I see you've packaged it up nicely into a command line gem. Just make sure to keep your README up to date as you refactor. :+1: :money_with_wings: :boom:

**Comment by wismer** [comment]
Yea, I'd have to really think about it this time around. Thank you for your feedback, it's been immensely helpful. It's given me new ideas on how to make this more useful where I work.
